

# Introduction {-}

The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

The Society for Ecosystem Restoration in Northern BC (SERNbc) is working together with the McLeod Lake Indian Band, the Peace Region Fish and Wildlife Compensation Program (FWCP), the Provincial Fish Passage Technical Working Group (FPTWG), road/rail tenure holders and other FWCP stakeholders/partners to prioritize, plan and fund the restoration of fish passage at Parsnip River watershed road crossing structure barriers. 

<br>

This project builds on Society for Ecosystem Restoration Northern BC (SERNbc) work in 2019 - 2020 and 2021 - 2022 which can be referenced [here](https://newgraphenvironment.github.io/Parsnip_Fish_Passage/) [@irvine2020ParsnipRiver] and [here](https://newgraphenvironment.github.io/fish_passage_parsnip_2021_reporting/) [@irvine2022PEAF22F3577DCARestoring]. Through this year's project activities (2022/2023) we engaged numerous project partners and were able to identify and catalyze fish passage restoration activities at multiple high priority sites. At PSCIS crossing 125179 - a tributary to Missinka River, culverts were replaced with a clear-span bridge.  Additionally, numerous sites were assessed in the field and two crossings on the Chuchinka-Table FSR were prioritized for replacement in 2024 - 2025 with engineering designs commissioned and construction materials purchased.

<br>

Through the ongoing development of open source analysis and data presentation tools (including pdf and web-hosted dashboard tools) we are identifying new restoration opportunities, clarifying restoration benefits, communicating with the broader community and implementing on the ground works. 

<br>

`r if(identical(gitbook_on, FALSE))knitr::asis_output("This report is available as pdf and as an online [interactive report](https://newgraphenvironment.github.io/fish_passage_peace_2022_reporting/) at https://newgraphenvironment.github.io/fish_passage_peace_2022_reporting/. We recommend viewing online as the web-hosted version contains more features and is more easily navigable. Please reference the website for the latest version number and download the most up to date pdf from https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/raw/master/docs/Peace2022.pdf")` 

`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

This document can be considered a living document.  Version numbers are logged for each release with modifications, enhancements and other changes tracked [here](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/blob/master/NEWS.md) with issues and proposed/planned enhancements tracked [here](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/issues). 

