# Recommendations

In addition to structure replacements and removals to restore connectivity - communications, research and monitoring are essential parts of any restoration initiative as they ensure that we identify the best and most efficient opportunities for fish passage restoration while incorporating adaptive management informed by traditional knowledge and real-time planning/monitoring data. Recommendations going forward include:

- Continue to engage partners to raise funds for remediations, identify sites for restoration, conduct remedial works and assess effectiveness of works. A particular focus obtaining all necessary financial commitments for the restoration of Fern Creek on the Chuchinka-Table FSR is recommended as although an engineering design have been commissioned by Canfor - their harvest plans in the greater watershed are
uncertain so replacement of the crossing in 2025 is not guaranteed.  Acquisition of additional funding to support this
project will help ensure that the crossing is replaced as planned.

- Continue to conduct detailed assessments where blockages are present and large amounts of habitat are potentially available within FWCP Peace Region watershed groups.  As timelines for remediations can be extensive, planning onerous and costs of remedial works significant, continuing assessments throughout the greater area will provide more options for remediation and engage additional funding partners (ex. Ministry of Transportation and Infrastructure, alternative forest licensees). Identifying areas of concern near the community of McLeod Lake is expected to further engage community members and most effectively promote restoration activities.

- Conduct effectiveness monitoring where sites have been remediated, where sites have been prioritized and where remediations are planned. Electrofishing surveys including tagging of target species with PIT tags are recommended to understand the extent of connectivity impairments, track fish movement/health over time and inform adaptive management. Detailed habitat assessments and acquisition of temperature data can be considered along with photo documentation of stream morphology near crossings. 
 
  - Conduct follow up monitoring at site 125179 in a tributary to the Missinka River watershed where the bridge was installed in 2022. Electrofishing with tagging of target species is recommended along with photo documentation of stream morphology near the bridge. Fish sampling in the adjacent similar sized stream [(PSCIS crossing 125180)](https://www.newgraphenvironment.com/Parsnip_Fish_Passage/03_Parsnip_report_125180.html) containing culverts ranked as barriers can provide reference site data for comparison.
  
  - As fish were tagged with PIT tags at site 125000 on the tributary to Parsnip River located on the Chuchinka-Arctic FSR in 2022 it is recommended that the site be reassessed with electrofishing in 2024 to provide valuable information regarding how the perched culvert may be impacting fish movement and health. 
  - Of particular priority for monitoring is PSCIS crossing [125231](https://www.newgraphenvironment.com/Parsnip_Fish_Passage/03_Parsnip_report_125231.html) on a tributary to the
  Table River as this remediation will be completed by Canfor in 2024. Fish sampling at this site before the actual
  remedial works took place in 2023 and follow up sampling following structure replacement will help demonstrate how
  project investments are positively impacting valuable watersheds in the FWCP Peace Region.
